export default {
  ko: {
    pageTitle: "회사소개",
    companyName: "제이앤비관세사무소",
    badgeIntro: "식품 수출입 통관·검역 전문 관세사",
    introTitle: "수출입의 모든 과정에 전문성을 더합니다",
    introBody:
      "식품검역, 수출입통관, 품목분류, FTA까지 — 검역·표시사항·원산지 중 한 곳만 막혀도 화물 전체가 멈춥니다. 통관이 시작되기 전에 리스크를 막습니다.",
    focusTitle: "전문분야",
    focusAreas: ["수출입통관", "식품검역", "품목분류(HS)", "FTA 원산지", "관세·외환조사 대응"],
    badgeContact: "담당 관세사",
    portraitAlt: "유혜인 관세사",
    staffName: "유혜인 관세사",
    staffTitle: "제이앤비관세사무소 대표",
    contactTitle: "연락처",
    phoneLabel: "전화.",
    phone: "032-834-7188",
    emailLabel: "이메일.",
    email: "hyein.yu@jnbglobal.kr",
    addressLabel: "주소.",
    address: "인천광역시 연수구 인천타워대로 323, 송도센트로드 A동 1716호",
    homepageLink: "제이앤비관세사무소 홈페이지 →",
  },
  en: {
    pageTitle: "About Us",
    companyName: "JNB Global Customs",
    badgeIntro: "Licensed Customs Broker — Food Import/Export Clearance & Quarantine Specialist",
    introTitle: "Bringing expertise to every stage of import and export",
    introBody:
      "From food quarantine and customs clearance to tariff classification and FTA origin — if any single link (quarantine, labeling, or origin) breaks down, the entire shipment stops moving. We stop risk before clearance even begins.",
    focusTitle: "Areas of Expertise",
    focusAreas: [
      "Import/Export Customs Clearance",
      "Food Quarantine",
      "Tariff Classification (HS)",
      "FTA Origin",
      "Customs & Foreign Exchange Investigation Response",
    ],
    badgeContact: "Lead Customs Broker",
    portraitAlt: "Hyein Yu, Customs Broker",
    staffName: "Hyein Yu, Customs Broker",
    staffTitle: "CEO, JNB Global Customs",
    contactTitle: "Contact",
    phoneLabel: "Phone.",
    phone: "+82-32-834-7188",
    emailLabel: "Email.",
    email: "hyein.yu@jnbglobal.kr",
    addressLabel: "Address.",
    address: "A-1716, Songdo Centroad, 323 Incheontower-daero, Yeonsu-gu, Incheon, South Korea",
    homepageLink: "JNB Global Customs Website →",
  },
  cn: {
    pageTitle: "公司简介",
    companyName: "JNB Global 关税事务所",
    badgeIntro: "食品进出口通关·检疫专业关税师",
    introTitle: "为进出口全流程提供专业保障",
    introBody:
      "从食品检疫、进出口通关、品目分类到FTA原产地——检疫、标示事项、原产地中只要有一处受阻，整批货物都会停滞。我们在通关开始之前就阻止风险。",
    focusTitle: "专业领域",
    focusAreas: ["进出口通关", "食品检疫", "品目分类（HS）", "FTA原产地", "关税·外汇调查应对"],
    badgeContact: "负责关税师",
    portraitAlt: "柳慧仁 关税师",
    staffName: "柳慧仁 关税师",
    staffTitle: "JNB Global 关税事务所 代表",
    contactTitle: "联系方式",
    phoneLabel: "电话.",
    phone: "+82-32-834-7188",
    emailLabel: "邮箱.",
    email: "hyein.yu@jnbglobal.kr",
    addressLabel: "地址.",
    address: "大韩民国仁川广域市延寿区仁川塔大路323号 松岛Centroad A栋1716号",
    homepageLink: "JNB Global 关税事务所官网 →",
  },
};
