export default {
  ko: {
    title: "수입 관부가세 계산기",
    subtitle: "관세청 관세율표 기준 · 참고용",
    description:
      "HS코드와 물품가격을 입력하면 관세·부가가치세·총 수입비용을 계산해드립니다. FTA 협정세율은 원산지증명서 구비를 전제로 적용됩니다.",
    hsCodeLabel: "HS코드",
    hsCodePlaceholder: "예: 8517130000",
    originLabel: "원산지 국가",
    priceLabel: "물품가격 (KRW, FOB 기준)",
    pricePlaceholder: "예: 1000000",
    freightLabel: "국제운임 (KRW)",
    insuranceLabel: "보험료 (KRW)",
    loadingLabel: "계산 중…",
    submitLabel: "세금 계산하기",
    errHsLength: "HS코드를 6자리 이상 입력해주세요.",
    errPrice: "물품가격을 입력해주세요.",
    errNoRates: "등록된 관세율 정보를 찾을 수 없습니다. HS코드를 다시 확인해주세요.",
    errNotAdValorem: "이 HS코드는 종량세 등 정률 계산이 어려운 품목입니다. 관세사 확인이 필요합니다.",
    appliedRateBadge: (rate, source) => `적용세율 ${rate}% (${source})`,
    tdCif: "CIF 가격",
    tdDuty: (rate) => `관세 (${rate}%)`,
    tdVat: "부가가치세 (10%)",
    tdTotalDuty: "총 납부세액",
    tdFinalCost: "최종 수입비용",
    ftaFallbackReason: (basicRate) =>
      `선택한 원산지에는 등록된 FTA 협정세율이 없어 기본세율/WTO협정세율 중 낮은 쪽을 적용했습니다 (기본세율 ${basicRate}%).`,
    disclaimer:
      "본 계산은 참고용이며 법적 효력이 없습니다. FTA 협정세율은 원산지증명서 구비 시에만 적용 가능하며, 정확한 세액은 관세사 확인이 필요합니다.",
    selectButton: "이 코드로 수입요건 조회 →",
  },
  en: {
    title: "Import Duty & VAT Calculator",
    subtitle: "Based on Korea Customs Service tariff schedule · For reference only",
    description:
      "Enter the HS code and item price to calculate customs duty, VAT, and total import cost. FTA preferential rates are applied on the assumption that a certificate of origin is available.",
    hsCodeLabel: "HS Code",
    hsCodePlaceholder: "e.g. 8517130000",
    originLabel: "Country of Origin",
    priceLabel: "Item Price (KRW, FOB basis)",
    pricePlaceholder: "e.g. 1000000",
    freightLabel: "International Freight (KRW)",
    insuranceLabel: "Insurance (KRW)",
    loadingLabel: "Calculating…",
    submitLabel: "Calculate Tax",
    errHsLength: "Please enter an HS code of at least 6 digits.",
    errPrice: "Please enter the item price.",
    errNoRates: "No registered tariff rate information found. Please double-check the HS code.",
    errNotAdValorem:
      "This HS code is subject to a specific (per-unit) duty rate that cannot be calculated as a percentage. Please consult a licensed customs broker.",
    appliedRateBadge: (rate, source) => `Applied rate ${rate}% (${source})`,
    tdCif: "CIF Value",
    tdDuty: (rate) => `Customs Duty (${rate}%)`,
    tdVat: "VAT (10%)",
    tdTotalDuty: "Total Tax Payable",
    tdFinalCost: "Final Import Cost",
    ftaFallbackReason: (basicRate) =>
      `No FTA preferential rate is registered for the selected country of origin, so the lower of the basic rate or WTO agreement rate was applied (basic rate ${basicRate}%).`,
    disclaimer:
      "This calculation is for reference only and has no legal effect. FTA preferential rates apply only when a certificate of origin is available, and the exact tax amount should be confirmed with a licensed customs broker.",
    selectButton: "Check import requirements for this code →",
  },
  cn: {
    title: "进口关税·增值税计算器",
    subtitle: "以韩国关税厅关税税率表为准 · 仅供参考",
    description:
      "输入HS编码和货物价格，即可计算关税、增值税及总进口成本。FTA协定税率的适用以具备原产地证明书为前提。",
    hsCodeLabel: "HS编码",
    hsCodePlaceholder: "例: 8517130000",
    originLabel: "原产地国家",
    priceLabel: "货物价格 (KRW，FOB基准)",
    pricePlaceholder: "例: 1000000",
    freightLabel: "国际运费 (KRW)",
    insuranceLabel: "保险费 (KRW)",
    loadingLabel: "计算中…",
    submitLabel: "计算税额",
    errHsLength: "请输入6位以上的HS编码。",
    errPrice: "请输入货物价格。",
    errNoRates: "未找到已登记的关税税率信息，请重新确认HS编码。",
    errNotAdValorem: "该HS编码适用从量税等，难以按比例计算，请咨询关务师确认。",
    appliedRateBadge: (rate, source) => `适用税率 ${rate}% (${source})`,
    tdCif: "CIF价格",
    tdDuty: (rate) => `关税 (${rate}%)`,
    tdVat: "增值税 (10%)",
    tdTotalDuty: "应纳税额合计",
    tdFinalCost: "最终进口成本",
    ftaFallbackReason: (basicRate) =>
      `所选原产地暂无已登记的FTA协定税率，因此已适用基本税率/WTO协定税率中较低的一方（基本税率 ${basicRate}%）。`,
    disclaimer:
      "本计算结果仅供参考，不具有法律效力。FTA协定税率仅在具备原产地证明书时方可适用，准确税额请咨询关务师确认。",
    selectButton: "以此编码查询进口要件 →",
  },
};
