export default {
  ko: {
    heading: "식품유형 확인",
    subtitle: "식품공전(식약처) 식품유형 분류표 · 272개 유형",
    note: "가공식품의 식품유형을 검색하거나 대분류에서 직접 선택해 확인하세요. 정확한 표시기준·규격은 식품의약품안전처 식품공전 원문 확인이 필요합니다.",
    searchLabel: "식품유형 검색",
    searchButton: "검색",
    searching: "검색 중…",
    resetButton: "초기화",
    selectedBadge: "선택한 식품유형",
    matchCount: (n) => `일치하는 식품유형 ${n}건을 찾았습니다.`,
    noMatch: "일치하는 식품유형을 찾지 못했습니다. 아래에서 대분류를 직접 선택해 보세요.",
    orBrowse: "또는 대분류에서 직접 선택하세요",
  },
  en: {
    heading: "Food Type Lookup",
    subtitle: "MFDS Food Code food type classification table · 272 types",
    note: "Search for the food type of a processed food, or browse the major categories directly. For exact labeling standards and specifications, consult the official MFDS Food Code text.",
    searchLabel: "Search food type",
    searchButton: "Search",
    searching: "Searching…",
    resetButton: "Reset",
    selectedBadge: "Selected food type",
    matchCount: (n) => `Found ${n} matching food type(s).`,
    noMatch: "No matching food type found. Try browsing a major category below.",
    orBrowse: "Or browse by major category",
  },
  cn: {
    heading: "食品类型查询",
    subtitle: "食品公典（食药处）食品类型分类表 · 272 种类型",
    note: "搜索加工食品的食品类型，或直接从大类中选择查看。准确的标示标准和规格请以食品医药品安全处食品公典原文为准。",
    searchLabel: "搜索食品类型",
    searchButton: "搜索",
    searching: "搜索中…",
    resetButton: "重置",
    selectedBadge: "已选食品类型",
    matchCount: (n) => `找到 ${n} 个匹配的食品类型。`,
    noMatch: "未找到匹配的食品类型。请在下方直接选择大类。",
    orBrowse: "或直接从大类中选择",
  },
};
