export default {
  ko: {
    partnerCredit: "제이앤비관세사무소 · 수입통관 전문 관세사",
    heroTitle: ["수입 통관,", "검색 한 번으로 확인하세요"],
    heroSub: "HS코드나 품목명만 입력하면 세관장확인 요건, 과거 부적합·회수 이력, 관련 법령 개정까지 한 화면에서 바로 보여드려요",
    stats: [
      { value: "1,425건", label: "부적합·회수 이력" },
      { value: "82건", label: "최근 법령 개정" },
      { value: "실시간", label: "관세청 요건 연동" },
    ],
    ctaPrimary: "지금 조회하기",
    ctaSecondary: "예시로 먼저 보기",
    demoHead: "화장품 원료 — 조회 예시",
    demoItems: [
      { label: "약사법 확인대상", pill: "요건 있음" },
      { label: "한국의약품수출입협회", pill: "승인기관" },
      { label: "한국동물약품협회", pill: "승인기관" },
      { label: "적용시작일", pill: "2020.04.06" },
    ],
    demoVerify: "관세청 원본 실시간 조회 완료",
    demoLink: "직접 조회 →",
    searchPlaceholder: "HS코드(예: 0202) 또는 품목명(예: 냉동 쇠고기)",
    searchBtn: "조회",
    searchBtnLoading: "조회 중",
    errorPrefix: "조회에 실패했습니다: ",
    tabReq: "수입요건",
    tabHist: "부적합·회수 이력",
    tabReg: "법령 업데이트",
    liveVerifiedStrip: "관세청 원본 데이터를 지금 이 순간 실시간으로 조회했습니다",
    emptyReq: "해당 HS코드에 등록된 세관장확인 요건이 없습니다. 코드 앞자리(류·호 단위)로 다시 검색해 보세요.",
    reqTableHead: ["HS부호", "확인법령", "요건승인기관", "적용시작"],
    emptyHist: "등록된 부적합·회수 이력이 없습니다.",
    badgeRejection: "통관 부적합",
    badgeRecall: "회수",
    companyUnknown: "업체 정보 미공개",
    reasonUnknown: "사유 미공개",
    emptyReg: "최근 90일 내 관련 법령 개정 이력이 없습니다.",
    amendmentDefault: "개정",
    effectivePrefix: "시행 ",
    hint1: "데이터 출처: 관세청 세관장확인대상물품 · 식약처 수입식품 부적합/회수 · 법제처 국가법령정보.",
    hint2: "수입요건은 검색 시점에 관세청 원본을 실시간으로 조회하며, 부적합·회수·법령은 매일 자동 갱신됩니다.",
    footerLine: (year) => `© ${year} 통관메이트 · Customs Mate · 제이앤비관세사무소`,
    footerDisclaimer: "본 서비스는 참고용이며 법적 효력이 없습니다. 최종 확인은 유니패스·식품안전나라·국가법령정보센터 원문을 기준으로 하시기 바랍니다.",
    dateUnknown: "미상",
  },
  en: {
    partnerCredit: "JNB Global Customs · Import Clearance Specialist Customs Brokers",
    heroTitle: ["Wondering if your import will clear customs?", "Find out with a single search"],
    heroSub: "Just enter an HS code or item name and instantly see customs-officer-confirmation requirements, past rejection/recall history, and related regulation updates — all on one screen.",
    stats: [
      { value: "1,425", label: "Rejection/Recall Records" },
      { value: "82", label: "Recent Regulation Updates" },
      { value: "Live", label: "Customs Requirement Sync" },
    ],
    ctaPrimary: "Search Now",
    ctaSecondary: "See an Example First",
    demoHead: "Cosmetic Ingredient — Search Example",
    demoItems: [
      { label: "Pharmaceutical Affairs Act Target", pill: "Requirement Applies" },
      { label: "Korea Pharmaceutical Traders Association", pill: "Approving Agency" },
      { label: "Korea Animal Health Products Association", pill: "Approving Agency" },
      { label: "Effective Date", pill: "2020.04.06" },
    ],
    demoVerify: "Live lookup of original Korea Customs data completed",
    demoLink: "Try it yourself →",
    searchPlaceholder: "HS code (e.g. 0202) or item name (e.g. frozen beef)",
    searchBtn: "Search",
    searchBtnLoading: "Searching",
    errorPrefix: "Search failed: ",
    tabReq: "Import Requirements",
    tabHist: "Rejection/Recall History",
    tabReg: "Regulation Updates",
    liveVerifiedStrip: "Original Korea Customs data was just looked up live, right now",
    emptyReq: "No customs-officer-confirmation requirements are registered for this HS code. Try searching with just the leading digits (chapter/heading level).",
    reqTableHead: ["HS Code", "Governing Law", "Approving Agency", "Effective From"],
    emptyHist: "No rejection/recall history is registered.",
    badgeRejection: "Customs Rejection",
    badgeRecall: "Recall",
    companyUnknown: "Company information not disclosed",
    reasonUnknown: "Reason not disclosed",
    emptyReg: "No related regulation amendments in the last 90 days.",
    amendmentDefault: "Amendment",
    effectivePrefix: "Effective ",
    hint1: "Data sources: Korea Customs Service's customs-officer-confirmation items · MFDS imported food rejection/recall data · Ministry of Government Legislation.",
    hint2: "Import requirements are looked up live from the original Korea Customs Service data at search time; rejection/recall and regulation data are refreshed automatically every day.",
    footerLine: (year) => `© ${year} Customs Mate · 통관메이트 · JNB Global Customs`,
    footerDisclaimer: "This service is for reference only and has no legal effect. For final confirmation, please refer to the original UNI-PASS, Food Safety Korea, and National Law Information Center sources.",
    dateUnknown: "Unknown",
  },
  cn: {
    partnerCredit: "JNB Global Customs · 进口通关专业报关行",
    heroTitle: ["进口通关能否顺利完成", "一次搜索即可确认"],
    heroSub: "只需输入HS编码或品名，即可在同一画面即时查看海关确认要件、过往不合格·召回记录及相关法规修订。",
    stats: [
      { value: "1,425件", label: "不合格·召回记录" },
      { value: "82件", label: "最新法规修订" },
      { value: "实时", label: "海关要件联动" },
    ],
    ctaPrimary: "立即查询",
    ctaSecondary: "先看示例",
    demoHead: "化妆品原料 — 查询示例",
    demoItems: [
      { label: "《药事法》确认对象", pill: "存在要件" },
      { label: "韩国医药品进出口协会", pill: "批准机构" },
      { label: "韩国动物药品协会", pill: "批准机构" },
      { label: "适用起始日", pill: "2020.04.06" },
    ],
    demoVerify: "已完成海关原始数据实时查询",
    demoLink: "立即查询 →",
    searchPlaceholder: "HS编码（例：0202）或品名（例：冷冻牛肉）",
    searchBtn: "查询",
    searchBtnLoading: "查询中",
    errorPrefix: "查询失败：",
    tabReq: "进口要件",
    tabHist: "不合格·召回记录",
    tabReg: "法规更新",
    liveVerifiedStrip: "此刻已实时查询海关原始数据",
    emptyReq: "该HS编码未登记海关确认要件。请尝试用编码前几位（章·目单位）重新查询。",
    reqTableHead: ["HS编码", "确认法规", "要件批准机构", "适用起始"],
    emptyHist: "未登记不合格·召回记录。",
    badgeRejection: "通关不合格",
    badgeRecall: "召回",
    companyUnknown: "企业信息未公开",
    reasonUnknown: "原因未公开",
    emptyReg: "最近90天内无相关法规修订记录。",
    amendmentDefault: "修订",
    effectivePrefix: "施行 ",
    hint1: "数据来源：韩国海关厅海关确认对象物品 · 食药处进口食品不合格/召回 · 法制处国家法令信息。",
    hint2: "进口要件在查询时实时调取海关原始数据，不合格·召回·法规信息每日自动更新。",
    footerLine: (year) => `© ${year} Customs Mate · 통관메이트 · JNB Global Customs`,
    footerDisclaimer: "本服务仅供参考，不具有法律效力。最终确认请以UNI-PASS、食品安全国家、国家法令信息中心原文为准。",
    dateUnknown: "未知",
  },
};
