export default {
  ko: {
    colHsCode: "HS부호",
    colNameKo: "한글품목명",
    colNameEn: "영문품목명",
    chapterTitle: (n) => `제${n}류`,
    count: (n) => `${n}건`,
    backToBrowse: "← 부·류 목록으로",
    chapterSearchPlaceholder: "이 류 안에서 코드 또는 품목명으로 검색",
    loading: "불러오는 중…",
    noResultsChapter: "일치하는 HS코드가 없습니다.",
    moreResultsChapter: "상위 120건만 표시됩니다 — 검색어로 좁혀보세요.",
    title: "HS코드 분류표",
    searchingAll: "전체 12,469건 중 검색",
    searchPlaceholder: "HS코드 앞자리(예: 0202) 또는 품목명(예: 냉동)으로 검색",
    noResultsSearch: "일치하는 HS코드가 없습니다. 검색어를 줄이거나 코드 앞자리로 시도해 보세요.",
    moreResultsSearch: "상위 60건만 표시됩니다 — 검색어를 더 구체적으로 입력해 좁혀보세요.",
    hierarchySubtitle: "부(21개)·류(97개) 계층 탐색",
    sectionLabel: (no) => `제${no}부`,
    chapterLabel: (no) => `${no}류`,
    frequentItems: "자주 조회되는 품목",
  },
  en: {
    colHsCode: "HS Code",
    colNameKo: "Korean Description",
    colNameEn: "English Description",
    chapterTitle: (n) => `Chapter ${n}`,
    count: (n) => `${n} items`,
    backToBrowse: "← Back to sections & chapters",
    chapterSearchPlaceholder: "Search within this chapter by code or item name",
    loading: "Loading…",
    noResultsChapter: "No matching HS codes.",
    moreResultsChapter: "Showing top 120 results — narrow your search.",
    title: "HS Code Classification",
    searchingAll: "Searching all 12,469 entries",
    searchPlaceholder: "Search by HS code prefix (e.g. 0202) or item name (e.g. frozen)",
    noResultsSearch: "No matching HS codes. Try a shorter search term or the code prefix.",
    moreResultsSearch: "Showing top 60 results — enter a more specific search term.",
    hierarchySubtitle: "Browse by section (21) and chapter (97)",
    sectionLabel: (no) => `Section ${no}`,
    chapterLabel: (no) => `Chapter ${no}`,
    frequentItems: "Frequently viewed items",
  },
  cn: {
    colHsCode: "HS编码",
    colNameKo: "韩文品名",
    colNameEn: "英文品名",
    chapterTitle: (n) => `第${n}章`,
    count: (n) => `${n}项`,
    backToBrowse: "← 返回类·章列表",
    chapterSearchPlaceholder: "在本章内按编码或品名搜索",
    loading: "加载中…",
    noResultsChapter: "没有匹配的HS编码。",
    moreResultsChapter: "仅显示前120项 — 请缩小搜索范围。",
    title: "HS编码分类表",
    searchingAll: "在全部12,469项中搜索",
    searchPlaceholder: "按HS编码前几位（如0202）或品名（如冷冻）搜索",
    noResultsSearch: "没有匹配的HS编码。请缩短搜索词或使用编码前几位重试。",
    moreResultsSearch: "仅显示前60项 — 请输入更具体的搜索词以缩小范围。",
    hierarchySubtitle: "按类（21个）·章（97个）层级浏览",
    sectionLabel: (no) => `第${no}部`,
    chapterLabel: (no) => `第${no}章`,
    frequentItems: "常查询品目",
  },
};
