export default {
  ko: {
    title: "영양성분 퍼센트 계산",
    subtitle: "식품 등의 표시ㆍ광고에 관한 법률 시행규칙 별표5 · 1일 영양성분 기준치",
    note: "측정한 영양성분 함량을 입력하면 1일 영양성분 기준치 대비 퍼센트(%)를 계산합니다. 반올림·표시 방법 등 세부 규정은 별표3을 함께 확인하세요.",
    requiredLabel: "필수 영양성분 (9)",
    calorieLabel: "열량 (kcal)",
    caloriePlaceholder: "1000kJ 이상 입력 시 자동으로 kcal 환산",
    optionalLabel: (n, total) => `선택 영양성분 (${n}/${total})`,
    addButton: "+ 추가",
    groupLabel: "기준 집단",
    groupAdult: "성인",
    groupInfant: "영유아 (만 1-2세)",
    submitButton: "퍼센트 계산하기",
    colNutrient: "영양성분",
    colInput: "입력값",
    colDailyValue: "1일 기준치",
    colPercent: "%기준치",
    noReference: "기준치 없음",
    footnote:
      "트랜스지방은 별표5에 1일 기준치가 없어 함량만 표시하고 퍼센트는 계산하지 않습니다. 영유아 모드는 별표5 비고에 따라 탄수화물·당류·단백질·지방 4종만 별도 기준치가 있고, 나머지는 국민영양관리법상 별도 섭취기준을 따라야 하므로 이 계산기에서는 제공하지 않습니다.",
  },
  en: {
    title: "Nutrition Facts Percentage Calculator",
    subtitle: "Food Labeling and Advertising Act Enforcement Rules, Table 5 · Daily Nutrient Reference Values",
    note: "Enter measured nutrient amounts to calculate the percentage (%) against the daily nutrient reference values. For rounding and display rules, also check Table 3.",
    requiredLabel: "Required Nutrients (9)",
    calorieLabel: "Energy (kcal)",
    caloriePlaceholder: "If entering 1000 kJ or more, it will auto-convert to kcal",
    optionalLabel: (n, total) => `Optional Nutrients (${n}/${total})`,
    addButton: "+ Add",
    groupLabel: "Reference Group",
    groupAdult: "Adult",
    groupInfant: "Infant (age 1-2)",
    submitButton: "Calculate Percentage",
    colNutrient: "Nutrient",
    colInput: "Amount",
    colDailyValue: "Daily Reference Value",
    colPercent: "% Daily Value",
    noReference: "No reference value",
    footnote:
      "Trans fat has no daily reference value under Table 5, so only the amount is shown and the percentage is not calculated. Under the infant setting, per the notes in Table 5, only carbohydrates, sugars, protein, and fat have separate reference values; the remaining nutrients follow separate intake standards under the National Nutrition Management Act and are not provided by this calculator.",
  },
  cn: {
    title: "营养成分百分比计算",
    subtitle: "《食品等标示ㆍ广告相关法律施行规则》附表5 · 每日营养成分基准值",
    note: "输入实测的营养成分含量，即可计算相对于每日营养成分基准值的百分比（%）。有关四舍五入、标示方法等详细规定，请一并参阅附表3。",
    requiredLabel: "必需营养成分（9项）",
    calorieLabel: "热量（kcal）",
    caloriePlaceholder: "输入1000kJ以上时将自动换算为kcal",
    optionalLabel: (n, total) => `可选营养成分（${n}/${total}）`,
    addButton: "+ 添加",
    groupLabel: "基准人群",
    groupAdult: "成人",
    groupInfant: "婴幼儿（1-2周岁）",
    submitButton: "计算百分比",
    colNutrient: "营养成分",
    colInput: "输入值",
    colDailyValue: "每日基准值",
    colPercent: "%基准值",
    noReference: "无基准值",
    footnote:
      "反式脂肪在附表5中没有每日基准值，因此仅显示含量，不计算百分比。婴幼儿模式下，根据附表5备注，仅碳水化合物、糖类、蛋白质、脂肪4项设有单独基准值，其余成分须遵循《国民营养管理法》规定的单独摄取标准，本计算器不提供相关计算。",
  },
};
