export default {
  ko: {
    rateLabels: {
      A: "기본",
      C: "WTO",
      FCN1: "한중FTA",
      FUS1: "한미FTA",
      FEU1: "한EU FTA",
      FVN1: "한베트남FTA",
      FAS1: "한아세안FTA",
      FRCJP1: "RCEP(한일)",
    },
    painPoints: [
      {
        title: "모호한 제품명",
        body: "고객은 “이어폰”, “히터”, “컵”처럼 짧게만 적습니다. 그 한 단어로 카테고리를 직접 고르게 하면, 잘못된 선택이 그대로 신고로 이어집니다.",
      },
      {
        title: "카테고리 오선택 → 분류 오류",
        body: "카테고리 하나를 잘못 고르면 요건도 함께 틀어집니다. 오분류의 책임은 결국 고객을 상대하는 쪽이 지게 됩니다.",
      },
      {
        title: "통관 지연 · 고객 이탈",
        body: "오분류로 통관이 지연되면 클레임과 재문의가 쌓이고, 응대 시간이 늘어날수록 고객은 다른 곳을 찾습니다.",
      },
    ],
    stats: [
      { value: "12,469건", label: "HS코드 마스터(관세청)" },
      { value: "75,574건", label: "관세율 데이터(기본·WTO·FTA 6종)" },
      { value: "무제한", label: "무료 · 로그인 불필요" },
      { value: "실시간", label: "세관장확인 요건 연동" },
    ],
    faqs: [
      {
        q: "confirmed와 provisional은 뭐가 다른가요?",
        a: "후보가 뚜렷하게 하나로 좁혀지면 confirmed(확정), “히터”처럼 재질·용도에 따라 다른 코드로 갈릴 수 있는 동명이물이면 provisional(잠정) + 확인 질문을 함께 드립니다. 잠정 배지일 때는 재질/용도를 채워 재조회하면 확정을 시도합니다.",
      },
      {
        q: "AI 분류와 실제 신고가 다를 수 있나요?",
        a: "네, 참고용입니다. 원큐는 관세청 공공데이터(HS코드 마스터 12,469건)에서 후보를 찾고 AI가 그 안에서 선택하는 방식이라 실존하지 않는 코드는 나오지 않지만, 관세사 실제 신고 이력으로 검증된 확정치는 아닙니다. 최종 신고 전 관세사 확인을 권장합니다.",
      },
      {
        q: "API로 연동할 수 있나요?",
        a: "지금은 웹 데모로 먼저 제공하고 있습니다. 배대지·포워더 시스템에 API로 직접 연동하고 싶으시면 아래 문의 폼으로 남겨주세요.",
      },
      {
        q: "세율과 수입요건도 같이 오나요?",
        a: "네. HS코드 후보마다 원산지 기준 관세율(기본·WTO·FTA)과 세관장확인 수입요건을 같은 응답에 함께 반환합니다.",
      },
      {
        q: "데이터는 어디서 오나요?",
        a: "관세청 세관장확인대상물품, HS코드 마스터, 품목번호별 관세율표, 식약처 수입식품 부적합·회수, 법제처 국가법령정보를 매일/매주 자동 수집하고, 여기에 Claude AI 분류 로직을 결합합니다.",
      },
    ],
    requestFailed: "요청 실패",
    eyebrow: "B2B 연동 · 배대지/포워더 전용 (준비 중)",
    title: "카테고리 선택 없이, 제품명 하나로 끝내세요",
    sub: "원큐(One Queue) API 한 번이면 HS코드 후보와 관세율, 수입요건까지 한 번에 돌아옵니다. 애매한 품명은 카테고리 목록 대신 속성 1개만 되물어 확정을 시도합니다.",
    painNote: "원큐는 카테고리 선택 화면 자체를 없애는 걸 지향합니다. 제품명만 받고, 필요할 때만 속성을 되묻는 방식입니다.",
    demoHeading: "지금 바로 테스트해보기",
    demoNote: "아래는 실제로 작동하는 데모입니다 — API 요청 한 번으로 HS코드·관세율·수입요건이 함께 돌아옵니다.",
    productNameLabel: "제품명 *",
    productNamePlaceholder: "예: 히터, 무선 이어폰(블루투스)",
    materialLabel: "재질 (선택)",
    materialPlaceholder: "예: 플라스틱, 세라믹",
    purposeLabel: "용도 (선택)",
    purposePlaceholder: "예: 가정용 실내난방, 산업용 설비",
    originLabel: "원산지 국가",
    requestSending: "요청 중…",
    requestSubmit: "API 요청 보내기",
    emptyPrompt: "제품명을 입력하고 API 요청을 보내주세요",
    loadingPrompt: "약 10초 내에 응답이 옵니다…",
    provisionalBadge: "잠정 (provisional)",
    confirmedBadge: "확정 (confirmed)",
    clarifyHeading: "확정하려면 한 가지만 더 알려주세요",
    answerPlaceholder: "답변을 입력하세요",
    requeryBtn: "재조회",
    noRateInfo: "등록된 관세율 정보 없음",
    reqCount: (n) => `수입요건 ${n}건:`,
    noReqInfo: "등록된 세관장확인 요건 없음",
    viewFullBtn: "이 코드로 수입요건 전체보기 →",
    noMatchNote: "일치하는 분류를 찾지 못했습니다.",
    honestyNote: "이 분류는 관세청 공공데이터와 AI 추론으로 생성되며, 실제 관세사 신고 이력으로 검증된 확정치가 아닙니다. 최종 신고 전에는 관세사 확인을 권장합니다.",
    faqHeading: "자주 묻는 질문",
    ctaHeading: "카테고리 선택 없는 통관, 원큐로 시작하세요",
    ctaBody: "API 연동 방식은 물량과 시스템에 맞춰 협의합니다. 아래 남겨주시면 확인 후 연락드립니다.",
    contactMeta: "제이엔비관세사무소 · 323 Incheontower-daero, A 1716 · 평일 07:30–18:00",
    leadDone: "문의가 접수됐습니다. 확인 후 연락드리겠습니다.",
    namePlaceholder: "이름",
    contactPlaceholder: "연락처 (선택)",
    emailPlaceholder: "이메일",
    messagePlaceholder: "문의 내용을 입력해주세요",
    sendingBtn: "전송 중…",
    sendBtn: "문의하기",
    sendError: "전송에 실패했습니다. 잠시 후 다시 시도해주세요.",
  },
  en: {
    rateLabels: {
      A: "Basic",
      C: "WTO",
      FCN1: "Korea-China FTA",
      FUS1: "Korea-US FTA",
      FEU1: "Korea-EU FTA",
      FVN1: "Korea-Vietnam FTA",
      FAS1: "Korea-ASEAN FTA",
      FRCJP1: "RCEP (Korea-Japan)",
    },
    painPoints: [
      {
        title: "Vague product names",
        body: "Customers only type short words like \"earbuds,\" \"heater,\" or \"cup.\" Letting them pick a category from that single word means a wrong choice flows straight into the declaration.",
      },
      {
        title: "Wrong category → misclassification",
        body: "Picking the wrong category also throws off the requirements. When misclassification happens, the party facing the customer ends up carrying the responsibility.",
      },
      {
        title: "Customs delays · customer churn",
        body: "A misclassification delays customs clearance, claims and repeat inquiries pile up, and the longer support takes, the more customers look elsewhere.",
      },
    ],
    stats: [
      { value: "12,469", label: "HS code master (Korea Customs Service)" },
      { value: "75,574", label: "Tariff rate records (basic, WTO, 6 FTA types)" },
      { value: "Unlimited", label: "Free · no login required" },
      { value: "Real-time", label: "Linked to customs-confirmation requirements" },
    ],
    faqs: [
      {
        q: "What's the difference between confirmed and provisional?",
        a: "When candidates clearly narrow down to one, the result is confirmed. For ambiguous items like \"heater,\" where the code can differ by material or purpose, we return provisional plus a clarifying question. When you see the provisional badge, filling in material/purpose and re-querying attempts a confirmed result.",
      },
      {
        q: "Can the AI classification differ from the actual declaration?",
        a: "Yes — treat it as a reference. OneQ finds candidates from Korea Customs Service open data (12,469 HS code master records) and lets AI choose among them, so it never returns a nonexistent code, but it isn't a confirmed value validated against actual licensed customs broker filing history. We recommend confirming with a licensed customs broker before final declaration.",
      },
      {
        q: "Can it be integrated via API?",
        a: "Right now we're offering it as a web demo first. If you'd like to integrate it directly into your fulfillment/forwarder system via API, please leave your details in the inquiry form below.",
      },
      {
        q: "Do tariff rates and import requirements come along with it?",
        a: "Yes. For each HS code candidate, the same response returns origin-based tariff rates (basic, WTO, FTA) together with customs-confirmation import requirements.",
      },
      {
        q: "Where does the data come from?",
        a: "We automatically collect Korea Customs Service customs-confirmation target items, the HS code master, the tariff schedule by item number, MFDS import food non-conformance/recall data, and Ministry of Government Legislation national statutes on a daily/weekly basis, and combine it with Claude AI classification logic.",
      },
    ],
    requestFailed: "Request failed",
    eyebrow: "B2B integration · for fulfillment centers/forwarders (coming soon)",
    title: "No category selection needed — just the product name",
    sub: "One call to the OneQ API returns HS code candidates, tariff rates, and import requirements all at once. For ambiguous product names, instead of a category list it asks just one follow-up question to try to confirm the result.",
    painNote: "OneQ is designed to remove the category-selection screen entirely. It only takes a product name, and asks for an attribute only when needed.",
    demoHeading: "Try it right now",
    demoNote: "This is a fully working demo below — one API request returns the HS code, tariff rates, and import requirements together.",
    productNameLabel: "Product name *",
    productNamePlaceholder: "e.g. heater, wireless earbuds (Bluetooth)",
    materialLabel: "Material (optional)",
    materialPlaceholder: "e.g. plastic, ceramic",
    purposeLabel: "Purpose (optional)",
    purposePlaceholder: "e.g. home indoor heating, industrial equipment",
    originLabel: "Country of origin",
    requestSending: "Requesting…",
    requestSubmit: "Send API request",
    emptyPrompt: "Enter a product name and send the API request",
    loadingPrompt: "Response arrives in about 10 seconds…",
    provisionalBadge: "Provisional",
    confirmedBadge: "Confirmed",
    clarifyHeading: "Tell us one more thing to confirm this",
    answerPlaceholder: "Enter your answer",
    requeryBtn: "Re-query",
    noRateInfo: "No registered tariff rate information",
    reqCount: (n) => `${n} import requirement${n === 1 ? "" : "s"}:`,
    noReqInfo: "No registered customs-confirmation requirements",
    viewFullBtn: "View all import requirements for this code →",
    noMatchNote: "No matching classification was found.",
    honestyNote: "This classification is generated from Korea Customs Service open data and AI inference, and is not a confirmed value validated against actual licensed customs broker filing history. We recommend confirming with a licensed customs broker before final declaration.",
    faqHeading: "Frequently asked questions",
    ctaHeading: "Start customs clearance without category selection, with OneQ",
    ctaBody: "The API integration approach is worked out to match your volume and system. Leave your details below and we'll get in touch after review.",
    contactMeta: "JNB Global Customs Brokers · 323 Incheontower-daero, A 1716 · Weekdays 07:30–18:00 (KST)",
    leadDone: "Your inquiry has been received. We'll review it and get back to you.",
    namePlaceholder: "Name",
    contactPlaceholder: "Contact (optional)",
    emailPlaceholder: "Email",
    messagePlaceholder: "Enter your inquiry",
    sendingBtn: "Sending…",
    sendBtn: "Send inquiry",
    sendError: "Failed to send. Please try again in a moment.",
  },
  cn: {
    rateLabels: {
      A: "基本税率",
      C: "WTO税率",
      FCN1: "韩中FTA",
      FUS1: "韩美FTA",
      FEU1: "韩欧盟FTA",
      FVN1: "韩越FTA",
      FAS1: "韩国-东盟FTA",
      FRCJP1: "RCEP(韩日)",
    },
    painPoints: [
      {
        title: "产品名称模糊",
        body: "客户通常只会输入“耳机”“暖风机”“杯子”这样的简短词语。若让他们仅凭一个词自行选择类别，错误的选择会直接反映到申报中。",
      },
      {
        title: "类别选错 → 分类错误",
        body: "只要类别选错一个，相关要件也会随之出错。误分类的责任最终会落在直接对接客户的一方身上。",
      },
      {
        title: "通关延误 · 客户流失",
        body: "误分类会导致通关延误，投诉和二次咨询随之增多，处理时间越长，客户就越可能转向其他服务商。",
      },
    ],
    stats: [
      { value: "12,469件", label: "HS编码主数据（韩国关税厅）" },
      { value: "75,574件", label: "关税率数据（基本·WTO·FTA共6种）" },
      { value: "不限次数", label: "免费 · 无需登录" },
      { value: "实时", label: "联动海关长确认要件" },
    ],
    faqs: [
      {
        q: "confirmed 和 provisional 有什么区别？",
        a: "当候选结果明确收敛为一个时返回 confirmed（确定）；若像“暖风机”这样可能因材质、用途不同而对应不同编码的同名异物，则返回 provisional（暂定）并附带确认问题。出现暂定标签时，补充材质/用途后重新查询即可尝试确定结果。",
      },
      {
        q: "AI分类结果与实际申报会有出入吗？",
        a: "会，请仅作参考。OneQ从韩国关税厅公开数据（HS编码主数据共12,469条）中查找候选项，再由AI在其中进行选择，因此不会出现不存在的编码，但并非经关务师实际申报记录验证的确定值。建议在最终申报前咨询关务师确认。",
      },
      {
        q: "可以通过API对接吗？",
        a: "目前我们先以网页演示的形式提供。如果您希望将其直接对接到海外仓/货代系统的API中，请通过下方咨询表单留言。",
      },
      {
        q: "税率和进口要件也会一起返回吗？",
        a: "是的。针对每个HS编码候选项，同一响应中会一并返回按原产地划分的关税率（基本·WTO·FTA）以及海关长确认进口要件。",
      },
      {
        q: "数据来自哪里？",
        a: "系统每日/每周自动采集韩国关税厅海关长确认对象物品、HS编码主数据、按品目编号划分的关税税率表、食品医药品安全处进口食品不合格·召回信息，以及法制处国家法令信息，并结合Claude AI分类逻辑进行处理。",
      },
    ],
    requestFailed: "请求失败",
    eyebrow: "B2B对接 · 海外仓/货代专用（筹备中）",
    title: "无需选择类别，只需输入产品名称",
    sub: "只需调用一次OneQ API，即可同时获取HS编码候选、关税率及进口要件。对于含义模糊的品名，系统不会展示类别列表，而是仅追加询问一项属性以尝试确定结果。",
    painNote: "OneQ致力于彻底取消类别选择界面，只接收产品名称，仅在必要时才追问相关属性。",
    demoHeading: "立即体验测试",
    demoNote: "以下是真实可用的演示——只需一次API请求，即可同时获取HS编码、关税率与进口要件。",
    productNameLabel: "产品名称 *",
    productNamePlaceholder: "例：暖风机、无线耳机（蓝牙）",
    materialLabel: "材质（选填）",
    materialPlaceholder: "例：塑料、陶瓷",
    purposeLabel: "用途（选填）",
    purposePlaceholder: "例：家用室内取暖、工业设备",
    originLabel: "原产地国家",
    requestSending: "请求中…",
    requestSubmit: "发送API请求",
    emptyPrompt: "请输入产品名称并发送API请求",
    loadingPrompt: "约10秒内即可获得响应…",
    provisionalBadge: "暂定 (provisional)",
    confirmedBadge: "确定 (confirmed)",
    clarifyHeading: "请再提供一项信息以确定结果",
    answerPlaceholder: "请输入您的回答",
    requeryBtn: "重新查询",
    noRateInfo: "暂无已登记的关税率信息",
    reqCount: (n) => `进口要件 ${n} 项：`,
    noReqInfo: "暂无已登记的海关长确认要件",
    viewFullBtn: "查看该编码的全部进口要件 →",
    noMatchNote: "未找到匹配的分类结果。",
    honestyNote: "该分类结果由韩国关税厅公开数据与AI推理生成，并非经关务师实际申报记录验证的确定值。建议在最终申报前咨询关务师确认。",
    faqHeading: "常见问题",
    ctaHeading: "无需选择类别的通关服务，即刻从OneQ开始",
    ctaBody: "API对接方式将根据您的业务量与系统情况另行协商。请在下方留言，我们确认后会尽快与您联系。",
    contactMeta: "JNB Global关务师事务所 · 323 Incheontower-daero, A 1716 · 工作日 07:30–18:00（韩国时间）",
    leadDone: "您的咨询已收到，我们确认后会尽快与您联系。",
    namePlaceholder: "姓名",
    contactPlaceholder: "联系方式（选填）",
    emailPlaceholder: "邮箱",
    messagePlaceholder: "请输入咨询内容",
    sendingBtn: "发送中…",
    sendBtn: "提交咨询",
    sendError: "发送失败，请稍后重试。",
  },
};
