export default {
  ko: {
    steps: ["수입업소", "제품정보", "원재료", "제조공정", "영양정보", "최종확인"],
    heading: "가공식품 의뢰",
    subheading: "수입식품 검역 정보 입력",
    note: "제조사 자료를 기다리지 않고, 수입자가 직접 검역 기초 정보를 정리해 제이앤비관세사무소로 전달할 수 있습니다.",
    doneBadge: "접수 완료",
    doneTitle: "검역 의뢰가 정상적으로 전달되었습니다",
    doneMeta: "제이앤비관세사무소에서 입력하신 이메일로 연락드립니다.",
    errorFileTooLarge: (mb) => `파일당 최대 ${mb}MB까지 첨부할 수 있습니다.`,
    errorTotalTooLarge: (mb) => `첨부파일 전체 용량은 ${mb}MB를 넘을 수 없습니다.`,
    labelImporterName: "수입업소명 *",
    labelImporterAddress: "수입업소 주소",
    labelImporterPhone: "수입업소 연락처",
    labelBizNo: "사업자번호",
    labelEmail: "이메일 *",
    labelBizRegFile: "사업자등록증",
    labelImportRegFile: "수입식품등의 수입판매업 영업등록증",
    fileHint: (maxFile, maxTotal) => `허용 형식: PDF, JPG, PNG, WEBP, HEIC, DOC, DOCX / 파일당 ${maxFile}MB, 전체 ${maxTotal}MB 이하`,
    labelProductName: "제품명 *",
    labelProductOrigin: "원산지",
    labelHsCode: "HS코드",
    labelPackagingUnit: "포장단위",
    labelIngredient: (n) => `원재료 ${n}`,
    placeholderIngredientName: "원재료명",
    placeholderIngredientOrigin: "원산지",
    placeholderIngredientRatio: "배합비율 (%)",
    deleteBtn: "삭제",
    addIngredientBtn: "+ 원재료 추가",
    labelProcess: "제조공정 설명",
    placeholderProcess: "원재료 투입부터 포장까지 제조공정을 순서대로 설명해주세요.",
    importerNameFallback: "수입업소명 미입력",
    reasonProductName: (name) => `제품명: ${name}`,
    productNameFallback: "미입력",
    ingredientsCount: (n) => `원재료 ${n}건`,
    attachmentsCount: (n) => `첨부파일 ${n}건`,
    attachmentsSizeSuffix: (mb) => ` (${mb}MB)`,
    prevBtn: "이전",
    nextBtn: "다음",
    submitBtn: "제출하기",
    submittingBtn: "전송 중…",
  },
  en: {
    steps: ["Importer", "Product Info", "Ingredients", "Manufacturing", "Nutrition", "Review"],
    heading: "Processed Food Request",
    subheading: "Import Food Quarantine Information",
    note: "Instead of waiting on manufacturer documents, importers can directly compile the basic quarantine information and submit it to J&B Global Customs.",
    doneBadge: "Submitted",
    doneTitle: "Your quarantine request has been submitted successfully",
    doneMeta: "J&B Global Customs will contact you at the email address you provided.",
    errorFileTooLarge: (mb) => `Each file can be up to ${mb}MB.`,
    errorTotalTooLarge: (mb) => `Total attachment size cannot exceed ${mb}MB.`,
    labelImporterName: "Importer Name *",
    labelImporterAddress: "Importer Address",
    labelImporterPhone: "Importer Phone",
    labelBizNo: "Business Registration No.",
    labelEmail: "Email *",
    labelBizRegFile: "Business Registration Certificate",
    labelImportRegFile: "Food Import & Sales Business Registration Certificate",
    fileHint: (maxFile, maxTotal) => `Accepted formats: PDF, JPG, PNG, WEBP, HEIC, DOC, DOCX / up to ${maxFile}MB per file, ${maxTotal}MB total`,
    labelProductName: "Product Name *",
    labelProductOrigin: "Country of Origin",
    labelHsCode: "HS Code",
    labelPackagingUnit: "Packaging Unit",
    labelIngredient: (n) => `Ingredient ${n}`,
    placeholderIngredientName: "Ingredient name",
    placeholderIngredientOrigin: "Country of origin",
    placeholderIngredientRatio: "Ratio (%)",
    deleteBtn: "Delete",
    addIngredientBtn: "+ Add Ingredient",
    labelProcess: "Manufacturing Process Description",
    placeholderProcess: "Please describe the manufacturing process in order, from raw material input to packaging.",
    importerNameFallback: "Importer name not entered",
    reasonProductName: (name) => `Product: ${name}`,
    productNameFallback: "Not entered",
    ingredientsCount: (n) => `${n} ingredient(s)`,
    attachmentsCount: (n) => `${n} attachment(s)`,
    attachmentsSizeSuffix: (mb) => ` (${mb}MB)`,
    prevBtn: "Back",
    nextBtn: "Next",
    submitBtn: "Submit",
    submittingBtn: "Submitting…",
  },
  cn: {
    steps: ["进口商", "产品信息", "原材料", "生产工艺", "营养信息", "最终确认"],
    heading: "加工食品委托",
    subheading: "填写进口食品检疫信息",
    note: "无需等待制造商提供资料，进口商可直接整理检疫基础信息并提交给J&B Global Customs（提伊安比关税事务所）。",
    doneBadge: "提交成功",
    doneTitle: "检疫委托已成功提交",
    doneMeta: "J&B Global Customs（提伊安比关税事务所）将通过您填写的邮箱与您联系。",
    errorFileTooLarge: (mb) => `每个文件最多可上传 ${mb}MB。`,
    errorTotalTooLarge: (mb) => `附件总容量不能超过 ${mb}MB。`,
    labelImporterName: "进口商名称 *",
    labelImporterAddress: "进口商地址",
    labelImporterPhone: "进口商联系方式",
    labelBizNo: "事业者登记号",
    labelEmail: "邮箱 *",
    labelBizRegFile: "事业者登记证",
    labelImportRegFile: "进口食品等进口销售业营业登记证",
    fileHint: (maxFile, maxTotal) => `支持格式：PDF、JPG、PNG、WEBP、HEIC、DOC、DOCX / 单个文件最大 ${maxFile}MB，总计不超过 ${maxTotal}MB`,
    labelProductName: "产品名称 *",
    labelProductOrigin: "原产地",
    labelHsCode: "HS编码",
    labelPackagingUnit: "包装单位",
    labelIngredient: (n) => `原材料 ${n}`,
    placeholderIngredientName: "原材料名称",
    placeholderIngredientOrigin: "原产地",
    placeholderIngredientRatio: "配比 (%)",
    deleteBtn: "删除",
    addIngredientBtn: "+ 添加原材料",
    labelProcess: "生产工艺说明",
    placeholderProcess: "请按顺序说明从原材料投入到包装的生产工艺流程。",
    importerNameFallback: "未填写进口商名称",
    reasonProductName: (name) => `产品名称：${name}`,
    productNameFallback: "未填写",
    ingredientsCount: (n) => `原材料 ${n} 项`,
    attachmentsCount: (n) => `附件 ${n} 个`,
    attachmentsSizeSuffix: (mb) => `（${mb}MB）`,
    prevBtn: "上一步",
    nextBtn: "下一步",
    submitBtn: "提交",
    submittingBtn: "提交中…",
  },
};
