export default {
  ko: {
    heading: "빠른 HS CODE 분류",
    subtitle: "AI 참고용 · 관세율·수입요건 통합 · 무료 공개 중 · 횟수 제한 없음",
    note: "제품명을 입력하면 AI가 우리 DB의 실제 HS코드 12,469건 중에서 후보를 찾고, 원산지 기준 관세율과 수입요건까지 한 화면에서 보여드립니다. 참고용이며, 정확한 분류는 관세사 확인이 필요합니다.",
    productNameLabel: "제품명",
    productNamePlaceholder: "예: 무선 마우스, 남성용 양모 슈트, 플라스틱 장난감",
    originLabel: "원산지 국가",
    langLabel: "언어",
    submitLoading: "분류 요청 중… (최대 10초)",
    submitButton: "HS CODE 분류 요청",
    errorDefault: "분류 요청에 실패했습니다",
    emptyPrompt: "제품명을 입력하고 분류 요청을 해주세요",
    loadingResults: "분류 결과와 관세율, 수입요건을 불러오는 중…",
    confidencePrefix: "신뢰도",
    confidenceLabel: { high: "높음", medium: "보통", low: "낮음" },
    extraLoading: "관세율·수입요건 조회 중…",
    tariffRateLabel: (source) => `관세율(${source}):`,
    noTariffRate: "등록된 관세율 정보 없음",
    requirementsCount: (n) => `수입요건 ${n}건 (클릭하면 상세 표시)`,
    requirementFallback: "요건",
    lawNameLabel: "확인법령",
    agencyNameLabel: "요건승인기관",
    effectiveFromLabel: "적용시작",
    unknown: "미상",
    noRequirements: "등록된 세관장확인 요건 없음",
    viewFullLink: "이 코드로 수입요건 전체보기 →",
    noMatch: "일치하는 분류를 찾지 못했습니다.",
  },
  en: {
    heading: "Quick HS Code Classification",
    subtitle: "AI reference only · Tariff rates & import requirements combined · Free, unlimited use",
    note: "Enter a product name and our AI will search 12,469 real HS codes in our database for candidates, showing origin-based tariff rates and import requirements on one screen. For reference only — consult a licensed customs broker to confirm the exact classification.",
    productNameLabel: "Product name",
    productNamePlaceholder: "e.g. wireless mouse, men's wool suit, plastic toy",
    originLabel: "Country of origin",
    langLabel: "Language",
    submitLoading: "Requesting classification… (up to 10s)",
    submitButton: "Request HS Code Classification",
    errorDefault: "Classification request failed",
    emptyPrompt: "Enter a product name and submit a classification request",
    loadingResults: "Loading classification results, tariff rates, and import requirements…",
    confidencePrefix: "Confidence",
    confidenceLabel: { high: "High", medium: "Medium", low: "Low" },
    extraLoading: "Looking up tariff rates and import requirements…",
    tariffRateLabel: (source) => `Tariff rate (${source}):`,
    noTariffRate: "No tariff rate on record",
    requirementsCount: (n) => `${n} import requirement(s) (click to view details)`,
    requirementFallback: "Requirement",
    lawNameLabel: "Governing law",
    agencyNameLabel: "Approving agency",
    effectiveFromLabel: "Effective from",
    unknown: "Unknown",
    noRequirements: "No customs officer confirmation requirements on record",
    viewFullLink: "View all import requirements for this code →",
    noMatch: "No matching classification found.",
  },
  cn: {
    heading: "快速HS编码分类",
    subtitle: "仅供AI参考 · 整合关税率与进口要件 · 免费开放使用 · 不限次数",
    note: "输入产品名称，AI会在我们数据库的12,469个实际HS编码中查找候选项，并在同一画面中显示按原产地计算的关税率和进口要件。仅供参考，准确分类请以报关行确认为准。",
    productNameLabel: "产品名称",
    productNamePlaceholder: "例：无线鼠标、男士羊毛西装、塑料玩具",
    originLabel: "原产地国家",
    langLabel: "语言",
    submitLoading: "分类请求中…（最长10秒）",
    submitButton: "请求HS编码分类",
    errorDefault: "分类请求失败",
    emptyPrompt: "请输入产品名称并提交分类请求",
    loadingResults: "正在加载分类结果、关税率和进口要件…",
    confidencePrefix: "可信度",
    confidenceLabel: { high: "高", medium: "中", low: "低" },
    extraLoading: "正在查询关税率和进口要件…",
    tariffRateLabel: (source) => `关税率（${source}）：`,
    noTariffRate: "暂无登记的关税率信息",
    requirementsCount: (n) => `${n} 项进口要件（点击查看详情）`,
    requirementFallback: "要件",
    lawNameLabel: "确认法令",
    agencyNameLabel: "要件批准机关",
    effectiveFromLabel: "适用起始日",
    unknown: "未知",
    noRequirements: "暂无登记的海关长确认要件",
    viewFullLink: "查看该编码的全部进口要件 →",
    noMatch: "未找到匹配的分类。",
  },
};
